dynare: use smaller test
This is an attempt to fix the dynare test that has been failing since years now.
The failures have been flacky, mostly due to numerical errors (nothing related to homebrew as far as I know).

The bkk.mod example has been in use since dynare has been added to homebrew-core in 2018.
I think I have seen this test fail hundreds of times since then.

Latest failues have been:
error: The generalized Schur (QZ) decomposition failed. For more information, see the documentation for Lapack function dgges: info=38, n=36. You can also run model_diagnostics to get more information on what may cause this problem.

Some other errors popped up in the past.

Using example1 (which is described in the quick-start page of the dynare documentation) is probably enought to test dynare.
I hope this test case is less prone to numerical errors.