glib: require python 3.11 for distutils
Python 3.12 removed distutils, which glib requires at build time.

The following error is observed when building glib:

    meson.build:2329:26:
    ERROR: <PythonExternalProgram 'python3' ->
    ['/usr/local/opt/python@3.12/bin/python3.12']>
    is not a valid python or it is missing distutils

Signed-off-by: David Aguilar <davvid@gmail.com>