ivtools: fix conflict with dialog
Fixes:
  Error: The `brew link` step did not complete successfully
  Could not symlink share/man/man3/Dialog.3
  Target /usr/local/share/man/man3/Dialog.3
  is a symlink belonging to dialog. You can unlink it:
    brew unlink dialog