BUGIFX: Added cairo as dependency
Building libdrm failed because of missing cairo.h:

```
tests/util/libutil.a.p/pattern.c.o.d -o tests/util/libutil.a.p/pattern.c.o -c ../tests/util/pattern.c
../tests/util/pattern.c:34:10: fatal error: cairo.h: No such file or directory
   34 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
```