terminalimageviewer: requires Catalina minimum (#94644)
Building on Mojave results in many errors like:
```
tiv.cpp:580:28: error: 'is_directory' is unavailable: introduced in macOS 10.15
```

Co-authored-by: Adrian Ho <aho+bruteforce@03s.net>