ghdl-llvm 6.0.0 (new formula)
Adds a new formula for ghdl as the cask is disabled, see:
https://formulae.brew.sh/cask/ghdl

Named it ghdl-llvm, as:
- there would be a conflict with the (disabled) cask
- this uses the llvm backend (GHDL can be built with different backends).

Issues with brew audit:
ghdl-llvm
  * line 14, col 5: https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnat-16.1.0-1/gnat-aarch64-darwin-16.1.0-1.tar.gz looks like a binary package, not a source archive; homebrew/core is source-only.
Error: 1 problem in 1 formula detected.