libtcod: requires Catalina minimum
Building on Mojave generates errors like:
```
../../samples/samples_cpp.cpp:1208:29: error: '~directory_iterator' is unavailable: introduced in macOS 10.15
```
No rebuilds needed, `CI-syntax-only`.