Fix `$CHILD_STATUS` issue
In order to use the `$CHILD_STATUS` variable we'd need to require
[`English`](http://ruby-doc.org/stdlib-2.4.0/libdoc/English/rdoc/English.html),
otherwise we'll see errors like:

```
$ brew install elixir
Error: undefined method `exitstatus' for nil:NilClass
```

This PR is just reverting this change.