aravis: Use meson build system
- As of version 7, this software builds with meson
  (https://github.com/AravisProject/aravis#installing-aravis), so the install
  step is a complete rewrite.
- This isn't entirely there yet - for me locally it complains about:

```
==> meson --prefix=/usr/local/Cellar/aravis/0.7.3 build
==> ninja -C build
Last 15 lines from /Users/issyl0/Library/Logs/Homebrew/aravis/02.ninja:
[77/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvgvdevice.c.o'.
[78/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvfakeinterface.c.o'.
[79/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvgvstream.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/arvgvstream.c.o
clang -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.62.5/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.5/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/glib/2.62.5/include -I/usr/include/libxml2 -I/usr/local/Cellar/libusb/1.0.23/include/libusb-1.0 -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -g '-DARAVIS_GETTEXT="aravis-0.8"' -DARAVIS_COMPILATION '-DARAVIS_DATA_DIR="/usr/local/Cellar/aravis/0.7.3/share/aravis-0.8"' '-DARAVIS_API_VERSION="0.8"' -MD -MQ 'src/25a6634@@aravis-0.8@sha/arvgvstream.c.o' -MF 'src/25a6634@@aravis-0.8@sha/arvgvstream.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/arvgvstream.c.o' -c ../src/arvgvstream.c
../src/arvgvstream.c:50:10: fatal error: 'linux/if_packet.h' file not found
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
[80/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvfakedevice.c.o'.
[81/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvfakestream.c.o'.
[82/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvfakecamera.c.o'.
[83/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvxmlschema.c.o'.
[84/144] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvuvinterface.c.o'.
ninja: build stopped: subcommand failed.
```