fix build error of minimal-racket
The error happened with Xcode 8.1 / MacOSX10.12.sdk.

My error message was like:

```
Xcode.app/.../Developer/SDKs/MacOSX10.12.sdk/usr/include/string.h:172:56:
error: expected ')'
__attribute__ ((availability (tvos , introduced = 10.0 .1 ) ) )
                                                       ^
```

which can be prevented with `__CUDACC__`:
(Definitily not the intention of this macro though)

```
 /* in string.h */
 #ifndef __CUDACC__
 __TVOS_AVAILABLE(10.0.1)
```