selenium-server-standalone 3.0.0
Update `selenium-server-standalone` to 3.0.0 released on 2016-10-13.
There are two errors from `brew audit`. The first, missing test, I am
leaving as is out of ignorance, however I am open to test suggestions.
The second issue is `devel version ... older than stable version....`
which I am leaving because presently there is no new devel version.

Selenium release index:
  http://selenium-release.storage.googleapis.com/index.html

Audit output:
```
$ brew audit --strict selenium-server-standalone
...
selenium-server-standalone:
  * A `test do` test block should be added
  * devel version 3.0.0-beta4 is older than stable version 3.0.0
Error: 2 problems in 1 formula
```