ec2-ami-tools: depends on ruby
Fixes:
Error: ==> Testing ec2-ami-tools
  ==> /home/linuxbrew/.linuxbrew/Cellar/ec2-ami-tools/1.5.7_2/bin/ec2-ami-tools-version
  /home/linuxbrew/.linuxbrew/Cellar/ec2-ami-tools/1.5.7_2/libexec/bin/ec2-ami-tools-version: line 6: ruby: command not found