yajl: Fix CFLAGS in pkgconfig
libvirt can't be built from source because yajl contains CFLAGS in
pkgconfig not matching layout of installed headers:

  ../src/util/virjson.c:36:11: fatal error: 'yajl/yajl_gen.h' file not
  found
  # include <yajl/yajl_gen.h>
            ^~~~~~~~~~~~~~~~~
  1 error generated.

Here's pkg-config output from meson logs:

  Called `/opt/homebrew/bin/pkg-config --cflags yajl` -> 0
  -I/opt/homebrew/Cellar/yajl/2.1.0/include/yajl

Here's actual layout of includedir:

  /opt/homebrew/Cellar/yajl/2.1.0/include/yajl/yajl_tree.h
  /opt/homebrew/Cellar/yajl/2.1.0/include/yajl/yajl_gen.h
  /opt/homebrew/Cellar/yajl/2.1.0/include/yajl/yajl_common.h
  /opt/homebrew/Cellar/yajl/2.1.0/include/yajl/yajl_version.h
  /opt/homebrew/Cellar/yajl/2.1.0/include/yajl/yajl_parse.h

Signed-off-by: Roman Bolshakov <r.bolshakov@yadro.com>