youtube-dl: change playlist in test
(I need to get better at choosing playlists that won't change. #38584)
The old playlist is no longer working:
    [youtube:playlist] LLnHXLLNHjNAnDQ50JANLG1g: Downloading webpage
    ERROR: This playlist does not exist.