cryptominisat: Fix Python build
Fixes:
==> cmake --install build
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/lib/cmake/cryptominisat5/cryptominisat5Config.cmake
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/lib/cmake/cryptominisat5/cryptominisat5Targets.cmake
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/lib/cmake/cryptominisat5/cryptominisat5Targets-release.cmake
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/lib/libcryptominisat5.5.8.dylib
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/lib/libcryptominisat5.dylib
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/include/cryptominisat5/cryptominisat_c.h
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/include/cryptominisat5/cryptominisat.h
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/include/cryptominisat5/solvertypesmini.h
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/include/cryptominisat5/dimacsparser.h
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/include/cryptominisat5/streambuffer.h
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/bin/cryptominisat5_simple
-- Installing: /usr/local/Cellar/cryptominisat/5.8.0_3/bin/cryptominisat5
running install
/usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build
running build_ext
running install_lib
copying build/lib.macosx-12-x86_64-3.10/pycryptosat.cpython-310-darwin.so -> /usr/local/lib/python3.10/site-packages
error: could not create '/usr/local/lib/python3.10/site-packages/pycryptosat.cpython-310-darwin.so': Operation not permitted
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version