isc-dhcp: remove explicitly specified `version`
Fixes

    ==> FAILED
    isc-dhcp:
      * Stable: version 4.4.2-P1 is redundant with version scanned from URL
    Error: 1 problem in 1 formula detected

While we're here:

- clean up some outdated style
- install configuration files into `etc` rather than `prefix/"etc"`
  because it's not necessary and users find this confusing (cf.
  Homebrew/discussions#2338)