remove namebench
namebench has not been updated upstream since 2011 and does not work under Python 3.x, so it is almost useless to keep in Homebrew. It will likely only cause a bad experience for end users, since it installs fine, but errors out on execution with:

      File "/usr/local/Cellar/namebench/1.3.1/libexec/bin/namebench", line 28
        print '* Your Python version (%s) is too old! Please upgrade to 2.6+!' % your_version
              ^
    SyntaxError: invalid syntax