verapdf: use openjdk@17
```
  Caused by: java.io.IOException: Error while instrumenting java/sql/Time.
	...
  Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
	...
  java.lang.instrument.IllegalClassFormatException: Error while instrumenting java/sql/Timestamp.
```