open-scene-graph: fix build when asio library is installed
When the asio library is installed, building open-scene-graph from
source will fail with:

    error: no member named 'error' in namespace 'asio::placeholders'

and other similar errors. This has already been fixed upstream but no
release has been made in several years, so we just pick up the upstream
patch.

Also see: https://github.com/openscenegraph/OpenSceneGraph/issues/921