[helmfile] Update helmfile tests
With helm 3.4.0 the repository used in tests has been deprecated.
```
Error: repo "https://kubernetes-charts.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/stable" instead
```

Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>