Bump clojure-lsp to 2021.01.28-03.03.16
Since this release name format has been changed, it needs to be manually updated.

```
brew bump-formula-pr clojure-lsp --tag=2021.01.28-03.03.16 --revision=fe50704d5e14009d4eeeb5a88a451d0ef4474838
...
Error: You need to bump this formula manually since the new version
and old version are both 20201207T142850.
```

See https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.01.28-03.03.16.