audiofile: deprecate
Does not build with newest gcc
SimpleModule.h:126:47: error: left operand of shift expression ‘(-1 << 15)’ is negative [-fpermissive]

Low download count over the last days
==> Analytics
install: 79 (30 days), 216 (90 days), 715 (365 days)
install-on-request: 39 (30 days), 112 (90 days), 365 (365 days)
build-error: 0 (30 days)

No new release since 2013, no new commits since 2016
See https://github.com/mpruett/audiofile/issues/53