terminalimageviewer: requires Catalina minimum
Building on Mojave results in many errors like:
```
tiv.cpp:580:28: error: 'is_directory' is unavailable: introduced in macOS 10.15
```