Bumping formula manually
When running `brew bump-formula-pr --url https://github.com/square/leakcanary/releases/download/v3.0-alpha-2/shark-cli-3.0-alpha-2.zip leakcanary-shark`

I got the following error:

> Error: You need to bump this formula manually since changing the version from 2.13 to 2 would be a downgrade.

It's weird that this is finding 2.13 when the latest update is 2.14. But more importantly, I'm not trying to upgrade to version 2 but to version 3 alpha 2. Looks like the version parsing isn't working.

So... I'm trying the manual PR as recommended by the root, although I'm pretty sure that's not going to work as I haven't updated the bottle / cellar entry (no idea how to compute that sha manually) and I also haven't solved the version issue. Halp!