Update tomcat@8 to v8.5.50
There is no way to execute command `brew install tomcat@8` because it refers to version which was removed 12/12/2019
Error from terminal:
```
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-8/v8.5.49/bin/apache-tomcat-8.5.49.tar.gz
==> Downloading from http://apache.ip-connect.vn.ua/tomcat/tomcat-8/v8.5.49/bin/apache-tomcat-8.5.49.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.49/bin/apache-tomcat-8.5.49.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.49/bin/apache-tomcat-8.5.49.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "tomcat@8"
Download failed: https://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.49/bin/apache-tomcat-8.5.49.tar.gz
```