c-kermit: depend on libxcrypt
Fixes:

Full linkage --test c-kermit output
  Unwanted system libraries:
    /lib/x86_64-linux-gnu/libcrypt.so.1
  Error: Calling linkage to libcrypt.so.1 is disabled! Use libcrypt.so.2 in the libxcrypt formula instead.