gmp: fix brew test/linkage issue on arm64
A branch statement in the arm64 flavour of `bdiv_q_1.asm` caused
the following error on `brew test`:

```
Undefined symbols for architecture arm64:
  "__gmpn_pi1_bdiv_q_1", referenced from:
      ___gmpn_bdiv_q_1 in libgmp.a(bdiv_q_1.o)
     (maybe you meant: ___gmpn_pi1_bdiv_q_1)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This commit fixes the issue by prepending `GSYM_PREFIX`.

It’s warranted to incorporate this patch early because a large number
of formulae depends on `gmp`, and waiting for an upstream fix would
introduce undue delay in testing those dependent formulae.