update to latest libgit2 0.24.1
`pip install pygit2` now requires libgit2 0.24.x:
```
    src/types.h:36:2: error: You need a compatible libgit2 version (v0.24.x)
```