lsyncd: depend on lua (Draft: Do not merge)
Follow up to https://github.com/Homebrew/homebrew-core/pull/65993.

See also https://github.com/axkibe/lsyncd/issues/502.

I've fixed a bunch of configuration and compile errors, but I'm left
with the following linker error:

    [100%] Linking C executable lsyncd
    /usr/local/Cellar/cmake/3.19.1/bin/cmake -E cmake_link_script CMakeFiles/lsyncd.dir/link.txt --verbose=1
    /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/lsyncd.dir/lsyncd.c.o CMakeFiles/lsyncd.dir/runner.c.o CMakeFiles/lsyncd.dir/defaults.c.o CMakeFiles/lsyncd.dir/fsevents.c.o -o lsyncd  /usr/local/opt/lua/lib/liblua.5.4.dylib
    Undefined symbols for architecture x86_64:
      "_lua_objlen", referenced from:
          _l_exec in lsyncd.c.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [lsyncd] Error 1
    make[1]: *** [CMakeFiles/lsyncd.dir/all] Error 2
    make: *** [all] Error 2

Does anyone have any ideas?