pyenv: change xz to depends_on
Change xz—formerly lzma—pyenv dependency from uses_from_macos to depends_on
because pyenv can't find any liblzma macOS system library but can find the
liblzma Homebrew library in /usr/local/lib.

Addresses the following pyenv warning message.
$ pyenv install 3.10.9
# ...
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?

And also the following Python error message.
$ python -c 'import lzma'
# ...
ModuleNotFoundError: No module named '_lzma'