Update license
In response to `brew audit --strict`:
```console
❯ brew audit --strict boxes
boxes:
  * Formula boxes contains deprecated SPDX licenses: ["GPL-2.0"].
    You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
    For a list of valid licenses check: https://spdx.org/licenses/
Error: 1 problem in 1 formula detected
```
and [verified by author](https://github.com/ascii-boxes/boxes/issues/77#issuecomment-811896990)